### ISSUE TITLE
[FEATURE REQUEST] Support K8S service creation

### ISSUE THREAD

**Issue by Rand0mF** [SAP-samples/btp-setup-automator#93]
### Which area is mainly impacted

Other

### Requested Feature

It would be great if btp-sa would also support service creation for K8S ([documentation](https://help.sap.com/docs/SERVICEMANAGEMENT/09cc82baadc542a688176dce601398de/0ccebd7cec24411dacd5ad17799534e0.html) for reference). Ideally as a native type for a usecase.json.
 

### Use Case/Scenario

Setup service for K8S environments on BTP. 

### Would you like to support us?

- [x] Yes, I would like to support you

**Comment by lechnerc77** [comment]
Currently the enhancements necessary are in evaluation. The current plan is to support the service instance creation for:

- Environment "cloud foundry" via CF CLI 
- Environment "kyma" via kubectl and the corresponding yaml files.
- Environment "other" via btp CLI

The detailed implementation would be hidden from the user of the BTP CLI (so no need to know which CLI will be used

In order to make the Kyma part work, we need to have the service operator (including the CRDs) rolled out to the Kyma cluster. This is currently in process (doa - not yet confirmed)

The creation of service keys/service bindings for the different environments follows the same approach

Known limitation for Kyma will be that the creation of the environment (i.e. the kyma cluster) and the creation of the services will not be possible in one go due to the OIDC logon mechanic of Kyma.

**Comment by lechnerc77** [comment]
The BTP service operator is available on Canary landscape, so the fun of implementing the change can begin :-)

**Comment by lechnerc77** [comment]
Implementation started; switched to branch <https://github.com/SAP-samples/btp-setup-automator/tree/service-creation-rework>

**Comment by lechnerc77** [comment]
Status:

- Creation of Services Instances via K8s Service Operator possible
- Creation of Services Bindings via K8s Service Operator possible
- Prune of Services Instances and Bindings via K8s Service Operator possible  

Next steps:

- Update of documentation for service creation on Kyma
- Implementation of Service creation for target environment "other" i.e. via BTP CLI

**Comment by lechnerc77** [comment]
The feature request is finished now. The scenario is supported now. 
Be aware of shortcomings in the authentication to Kyma (issue of Kyma not of BTPSA) as described here:

* [FAQ - I cannot execute kubectl commands after the Kyma runtime got provisioned. Is this a bug?](https://github.com/SAP-samples/btp-setup-automator/blob/main/docs/FAQ.md#i-cannot-execute-kubectl-commands-after-the-kyma-runtime-got-provisioned-is-this-a-bug)
* [FAQ - How can I create a service account?](https://github.com/SAP-samples/btp-setup-automator/blob/main/docs/FAQ.md#how-can-i-create-a-service-account)

The Docker Image is not yet built, so the functionality is only supported via build from source. I update the issue once the Docker image is available

**Comment by lechnerc77** [comment]
Docker Image is built and available in the GH packages
